export const CASE_STATUS = Object.freeze({
  DRAFT: 'draft',
  AWAITING_AUTHORITY: 'awaiting_authority',
  READY_TO_ASSIGN: 'ready_to_assign',
  AWAITING_AGENT: 'awaiting_agent',
  IN_FIELD: 'in_field',
  ATTEMPT_REVIEW: 'attempt_review',
  CUSTODY_REVIEW: 'custody_review',
  PAYMENT_PENDING: 'payment_pending',
  PAYMENT_CONFIRMED: 'payment_confirmed',
  RELEASE_ISSUED: 'release_issued',
  CLOSED: 'closed',
  CANCELLED: 'cancelled',
});

export const PERMISSIONS = Object.freeze({
  ORGANIZATION_MANAGE: 'organization.manage',
  MEMBER_MANAGE: 'member.manage',
  ROLE_MANAGE: 'role.manage',
  AGENT_MANAGE: 'agent.manage',
  IMPORT_MANAGE: 'import.manage',
  ACCOUNT_MANAGE: 'account.manage',
  CASE_CREATE: 'case.create',
  AUTHORITY_APPROVE: 'authority.approve',
  CASE_ASSIGN: 'case.assign',
  ASSIGNMENT_RESPOND: 'assignment.respond',
  ATTEMPT_SUBMIT: 'attempt.submit',
  ATTEMPT_REVIEW: 'attempt.review',
  CUSTODY_SUBMIT: 'custody.submit',
  CUSTODY_REVIEW: 'custody.review',
  PAYMENT_CONFIRM: 'payment.confirm',
  RELEASE_ISSUE: 'release.issue',
  RELEASE_REVOKE: 'release.revoke',
  RELEASE_CLOSE: 'release.close',
  REPORT_EXPORT: 'report.export',
  AUDIT_VIEW: 'audit.view',
  RETENTION_MANAGE: 'retention.manage',
});

export const ROLE_TEMPLATES = Object.freeze({
  owner: Object.freeze(Object.values(PERMISSIONS)),
  manager: Object.freeze([
    PERMISSIONS.MEMBER_MANAGE,
    PERMISSIONS.AGENT_MANAGE,
    PERMISSIONS.IMPORT_MANAGE,
    PERMISSIONS.ACCOUNT_MANAGE,
    PERMISSIONS.CASE_CREATE,
    PERMISSIONS.AUTHORITY_APPROVE,
    PERMISSIONS.CASE_ASSIGN,
    PERMISSIONS.ATTEMPT_REVIEW,
    PERMISSIONS.CUSTODY_REVIEW,
    PERMISSIONS.PAYMENT_CONFIRM,
    PERMISSIONS.RELEASE_ISSUE,
    PERMISSIONS.RELEASE_REVOKE,
    PERMISSIONS.RELEASE_CLOSE,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.AUDIT_VIEW,
  ]),
  staff: Object.freeze([
    PERMISSIONS.IMPORT_MANAGE,
    PERMISSIONS.ACCOUNT_MANAGE,
    PERMISSIONS.CASE_CREATE,
  ]),
  agent: Object.freeze([
    PERMISSIONS.ASSIGNMENT_RESPOND,
    PERMISSIONS.ATTEMPT_SUBMIT,
    PERMISSIONS.CUSTODY_SUBMIT,
  ]),
});

export function hasPermission(permissions, permission) {
  return Array.isArray(permissions) && permissions.includes(permission);
}

const transitions = new Map([
  [CASE_STATUS.DRAFT, [CASE_STATUS.AWAITING_AUTHORITY, CASE_STATUS.CANCELLED]],
  [CASE_STATUS.AWAITING_AUTHORITY, [CASE_STATUS.READY_TO_ASSIGN, CASE_STATUS.CANCELLED]],
  [CASE_STATUS.READY_TO_ASSIGN, [CASE_STATUS.AWAITING_AGENT, CASE_STATUS.CANCELLED]],
  [CASE_STATUS.AWAITING_AGENT, [CASE_STATUS.IN_FIELD, CASE_STATUS.READY_TO_ASSIGN, CASE_STATUS.CANCELLED]],
  [CASE_STATUS.IN_FIELD, [CASE_STATUS.ATTEMPT_REVIEW, CASE_STATUS.CUSTODY_REVIEW, CASE_STATUS.CANCELLED]],
  [CASE_STATUS.ATTEMPT_REVIEW, [CASE_STATUS.IN_FIELD, CASE_STATUS.READY_TO_ASSIGN, CASE_STATUS.CANCELLED]],
  [CASE_STATUS.CUSTODY_REVIEW, [CASE_STATUS.IN_FIELD, CASE_STATUS.PAYMENT_PENDING, CASE_STATUS.CANCELLED]],
  [CASE_STATUS.PAYMENT_PENDING, [CASE_STATUS.PAYMENT_CONFIRMED]],
  [CASE_STATUS.PAYMENT_CONFIRMED, [CASE_STATUS.RELEASE_ISSUED]],
  [CASE_STATUS.RELEASE_ISSUED, [CASE_STATUS.PAYMENT_CONFIRMED, CASE_STATUS.CLOSED]],
]);

export function canTransition(from, to) {
  return transitions.get(from)?.includes(to) ?? false;
}
